In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size=10000

### One Hot representation

In [ ]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr
# here for every word one hot encoding is done

[[8218, 6854, 6388, 6081],
 [8218, 6854, 6388, 1310],
 [8218, 7237, 6388, 6031],
 [386, 3430, 4403, 5451, 6839],
 [386, 3430, 4403, 5451, 7503],
 [9190, 8218, 357, 6388, 8300],
 [1050, 7810, 8122, 5451]]

### Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences   #this pad sequences make the sentences of equal size 
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8

In [ ]:
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen= sent_length)
embedded_docs
# here all sentences are of equal size now

array([[   0,    0,    0,    0, 8218, 6854, 6388, 6081],
       [   0,    0,    0,    0, 8218, 6854, 6388, 1310],
       [   0,    0,    0,    0, 8218, 7237, 6388, 6031],
       [   0,    0,    0,  386, 3430, 4403, 5451, 6839],
       [   0,    0,    0,  386, 3430, 4403, 5451, 7503],
       [   0,    0,    0, 9190, 8218,  357, 6388, 8300],
       [   0,    0,    0,    0, 1050, 7810, 8122, 5451]], dtype=int32)

In [10]:
# feature representation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

2024-12-18 11:08:04.379218: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 496ms/step


array([[[ 1.92280151e-02, -4.31989916e-02,  1.67938955e-02,
          1.58510096e-02, -1.01072080e-02,  8.31242651e-03,
          2.95908935e-02,  1.63585804e-02,  4.17862870e-02,
         -1.83710232e-02],
        [ 1.92280151e-02, -4.31989916e-02,  1.67938955e-02,
          1.58510096e-02, -1.01072080e-02,  8.31242651e-03,
          2.95908935e-02,  1.63585804e-02,  4.17862870e-02,
         -1.83710232e-02],
        [ 1.92280151e-02, -4.31989916e-02,  1.67938955e-02,
          1.58510096e-02, -1.01072080e-02,  8.31242651e-03,
          2.95908935e-02,  1.63585804e-02,  4.17862870e-02,
         -1.83710232e-02],
        [ 1.92280151e-02, -4.31989916e-02,  1.67938955e-02,
          1.58510096e-02, -1.01072080e-02,  8.31242651e-03,
          2.95908935e-02,  1.63585804e-02,  4.17862870e-02,
         -1.83710232e-02],
        [-3.98421995e-02,  4.39277403e-02,  4.16189916e-02,
         -4.98394854e-02,  4.34148945e-02, -1.27005689e-02,
         -1.97272897e-02,  4.60070707e-02,  1.124586

In [15]:
# first sentence 
embedded_docs[0]

array([   0,    0,    0,    0, 8218, 6854, 6388, 6081], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 55ms/step


array([[ 0.01922802, -0.04319899,  0.0167939 ,  0.01585101, -0.01010721,
         0.00831243,  0.02959089,  0.01635858,  0.04178629, -0.01837102],
       [ 0.01922802, -0.04319899,  0.0167939 ,  0.01585101, -0.01010721,
         0.00831243,  0.02959089,  0.01635858,  0.04178629, -0.01837102],
       [ 0.01922802, -0.04319899,  0.0167939 ,  0.01585101, -0.01010721,
         0.00831243,  0.02959089,  0.01635858,  0.04178629, -0.01837102],
       [ 0.01922802, -0.04319899,  0.0167939 ,  0.01585101, -0.01010721,
         0.00831243,  0.02959089,  0.01635858,  0.04178629, -0.01837102],
       [-0.0398422 ,  0.04392774,  0.04161899, -0.04983949,  0.04341489,
        -0.01270057, -0.01972729,  0.04600707,  0.01124587,  0.04938604],
       [-0.02228795,  0.004415  ,  0.02076895, -0.01850352, -0.00361661,
         0.03584992, -0.03564801,  0.04789774,  0.04442037, -0.04018683],
       [-0.02298448, -0.02105016, -0.03080524,  0.0146125 ,  0.04080487,
         0.04692743, -0.00996933, -0.01607222